"""Exercise upstream v3 writers and project tooling on real temporary files."""

import json

import pytest

from control.collection.dataset import open_dataset
from control.collection.deletion import EpisodeDeleter
from control.collection.pipeline import run_collection
from control.config import load_config
from data_analysis.dataset_io import episode_dataframe, episode_paths, episode_rows
from data_analysis.merge_lerobot_datasets import merge_datasets
from replay.scripts.read_audio import read_audio
from replay.scripts.read_dataset import read_dataset


@pytest.fixture
def v3_collection(tmp_path):
    config = load_config()
    config["dataset"].update(root=str(tmp_path), date="upgrade")
    config["camera"]["image_hw"] = 32
    config["audio"].update(enabled=True, vad_enabled=False)
    for index in range(3):
        config["dataset"]["instruction"] = f"Task {index}"
        run_collection(config, dry_run=True, max_steps=20)
    return config, tmp_path / "franka_lerobot_upgrade"


def test_v3_deletion_rewrites_shared_data_and_sidecars(v3_collection):
    config, root = v3_collection
    before = read_dataset(root)
    result = EpisodeDeleter(root).delete_episode(1)
    after = read_dataset(root)
    assert after["version"] == "v3.0" and after["total_episodes"] == 2
    assert after["total_frames"] == before["total_frames"] - result.deleted_frames
    assert after["episodes"][1]["tasks"] == ["Task 2"]
    assert read_audio(root, 1)["sample_rate"] == 16000
    sync = json.loads((root / "audio/episode_000001.sync.json").read_text())
    assert sync["episode_index"] == 1 and sync["action_trace"] == "episode_000001.actions.jsonl"
    dataset, _ = open_dataset(config)
    dataset.finalize()
    EpisodeDeleter(root).delete_episode(1)
    EpisodeDeleter(root).delete_episode(0)
    assert read_dataset(root)["total_episodes"] == 0
    dataset, _ = open_dataset(config)
    dataset.finalize()


def test_v3_task_rewrite_updates_every_episode_in_shared_shard(v3_collection):
    from lerobot.datasets import LeRobotDataset

    from data_analysis.dataset_io import rewrite_v3_tasks

    _, root = v3_collection
    prompts = {0: "Command A", 1: "Command B", 2: "Command A"}
    result = rewrite_v3_tasks(root, prompts)
    assert result["num_tasks"] == 2
    paths = episode_paths(root)
    for row in episode_rows(root):
        index = row["episode_index"]
        assert row["tasks"] == [prompts[index]]
        assert set(episode_dataframe(paths[index], index)["task_index"]) == {int(index == 1)}
    dataset = LeRobotDataset(root.name, root=root, video_backend="pyav")
    assert dataset.meta.get_task_index("Command B") == 1


def test_v3_merge_retains_audio_and_trace(v3_collection, tmp_path):
    _, root = v3_collection
    output = merge_datasets(
        [str(root), str(root)], output_name="merged", data_root=tmp_path, overwrite=False
    )
    info = read_dataset(output)
    assert info["total_episodes"] == 6
    assert info["total_frames"] == 2 * read_dataset(root)["total_frames"]
    for index in range(6):
        assert read_audio(output, index)["sample_rate"] == 16000
        assert (output / f"episode_{index:06d}.actions.jsonl").is_file()
        sync = json.loads((output / f"audio/episode_{index:06d}.sync.json").read_text())
        assert sync["episode_index"] == index
        assert sync["action_trace"] == f"episode_{index:06d}.actions.jsonl"


def test_legacy_recording_requires_explicit_conversion(tmp_path):
    config = load_config()
    config["dataset"].update(root=str(tmp_path), date="legacy")
    root = tmp_path / "franka_lerobot_legacy"
    (root / "meta").mkdir(parents=True)
    schema = __import__("control.collection.dataset", fromlist=["features"]).features(
        224, "ee", False
    )
    (root / "meta/info.json").write_text(
        json.dumps({"codebase_version": "v2.1", "fps": 30, "features": schema})
    )
    with pytest.raises(ValueError, match="convert a copy"):
        open_dataset(config)


def test_resuming_converted_stats_keeps_metadata_shards_compatible(v3_collection):
    import pyarrow.parquet as pq
    from lerobot.datasets import LeRobotDataset

    config, root = v3_collection
    # Converted v2.1 statistics lack the quantiles generated by a modern writer.
    for path in (root / "meta/episodes").glob("chunk-*/file-*.parquet"):
        table = pq.ParquetFile(path).read()
        columns = [key for key in table.column_names if not key.rsplit("/", 1)[-1].startswith("q")]
        pq.write_table(table.select(columns).replace_schema_metadata(None), path)
    run_collection(config, dry_run=True, max_steps=20)
    dataset = LeRobotDataset(root.name, root=root, video_backend="pyav")
    assert dataset.num_episodes == 4
    paths = list((root / "meta/episodes").glob("chunk-*/file-*.parquet"))
    schemas = [pq.read_schema(path) for path in paths]
    assert all(schema.equals(schemas[0], check_metadata=False) for schema in schemas)
